import "./globals.css";
import type { Metadata } from "next";
import localFont from 'next/font/local'
 
const myFont = localFont({
  src: '../fonts/WantedSansVariable.woff2',
})
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={myFont.className}>
      <body>{children}</body>
    </html>
  );
}
